### ISSUE TITLE
[feature request] config option to allow cheaper recipe

### ISSUE THREAD

**Issue by Zygus42** [Hennamann/ModJam-5#1]
Given that people want to lay very long railroad underwater, and there's never enough slime (unless you use a lot of slime islands in tinkers mod), it would be nice to have the option to have a cheaper version of the recipe - maybe 8 normal rails + slime ball = 8 underwater rails ?

**Comment by Hennamann** [comment]
Good idea, can guarantee that the 1.16.5/1.18 versions will get a cheaper recipe, i´ll see about getting it changed in the 1.12 version as well.

**Comment by Hennamann** [comment]
New version for 1.12 and 1.16 with the suggested cheaper recipe has been added to curseforge.
