### ISSUE TITLE
some feedback

### ISSUE THREAD

**Issue by Zygus42** [Hennamann/ModJam-5#2]
This is the glass covered version and looks nice when it's only 1 space deep, as the entire 2 block height looks full of air covered by glass:
![2018-05-01_13 17 30](https://user-images.githubusercontent.com/20757445/39462192-5055c4a8-4d42-11e8-925d-f77d0c9a9e4a.png)

But the same rails in deeper water look like the entire 2 blocks are full of water and makes it so you can't see much.  Nowhere near as nice:
![2018-05-01_13 17 43](https://user-images.githubusercontent.com/20757445/39462193-5137ccd6-4d42-11e8-9a16-0f542709a1c8.png)

The basic rail would look a lot more aesthetically pleasing if the rail block was covered in water rather than air:
![2018-05-01_13 18 17](https://user-images.githubusercontent.com/20757445/39462194-51e980d4-4d42-11e8-8634-cb8852618046.png)

Other than that, only need a powered rail which I know you have planned, and this will be an excellent modpack addition !   I love underwater rail networks !

**Comment by Hennamann** [comment]
All of these have been or will be fixed with the soon to be releases 1.16.5/1.18 releases.
Unfortunatley i do not think i will have the time to get these fixes into the 1.12 version.

**Comment by Hennamann** [comment]
All of these are fixed for both the 1.16.5 version and the 1.18.1 version.
